<?php

// This file is generated by Composer
require_once __DIR__ . '/vendor/autoload.php';

$client = new \Github\Client();
	
	
	$client->authenticate($_POST['username'], $_POST['password'], Github\Client::AUTH_HTTP_PASSWORD);
	$repository = $client->api('repo')->forks()->create($_POST['owned'], $_POST['reponame']);
	
