<?php

// This file is generated by Composer
require_once __DIR__ . '/vendor/autoload.php';

$client = new \Github\Client();


$username = (string)$_POST["username"];
$reponame = (string)$_POST["reponame"];


//encode readme.md content

$readme = $client->api('repo')->contents()->readme($username, $reponame, $reference);

echo json_encode(base64_decode($readme[content]));





	
	


